# Generated by Django 5.1.7 on 2025-05-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0001_initial'),
        ('produtos', '0002_alter_produto_descricao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemCarrinho',
            new_name='CarItem',
        ),
        migrations.RenameField(
            model_name='caritem',
            old_name='carinho',
            new_name='carrinho',
        ),
    ]
