# Generated by Django 5.1.7 on 2025-05-22 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_rename_itemcarrinho_caritem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caritem',
            name='preco',
        ),
    ]
